services:
  - type: web
    name: timebeacon-app
    env: node
    plan: free
    buildCommand: npm install && npx vite build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION  
        value: "20"
    domains:
      - app.timebeacon.io