name: Deploy Backend to Railway

on:
  push:
    branches: [ main ]
    paths: 
      - 'backend-server.js'
      - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Railway
        uses: railway-app/railway-app@v1
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: timebeacon-backend